import type { Metadata } from "next";
import "./globals.css";
import { cascadia, dirtyline, montserrat } from "../fonts/font";
import SmoothScroll from "../contexts/ScrollSmoth";
import { DeviceProvider } from '@/contexts/DeviceContext'
import CursorInit from "@/utils/customCursor/initCursor";

export const metadata: Metadata = {
  title: "Ludo portfolio",
  description: "Generated by create next app",//TODO cambia descriptio e inserisci la seo
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${dirtyline.variable} ${cascadia.variable} antialiased`}
      >
          <SmoothScroll>
            <DeviceProvider>
              <CursorInit />
              {children}
            </DeviceProvider>
          </SmoothScroll>
      </body>
    </html>
  );
}
