import type { Metadata } from "next";
import "./globals.css";
import { cascadia, dirtyline, montserrat } from "./fonts/font";
import SmoothScroll from "./providers/ScrollSmoth";

export const metadata: Metadata = {
  title: "Ludo portfolio",
  description: "Generated by create next app",//TODO cambia descriptio e inserisci la seo
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${dirtyline.variable} ${cascadia.variable} antialiased`}
      >
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
